### ISSUE TITLE
Licenses, LICENSE and LICENCE?

### ISSUE THREAD

**Issue by pombredanne** [isaacs/read#27]
@isaacs your package.json states this component is ISC-licensed. Yet you have two license files at the root: 
- a LICENCE file containing a BSD-Simplified aka BSD-2-Clause license text
- a LICENSE file containing an ISC license text.

Which one applies? both?
Thanks!

**Comment by isaacs** [comment]
Thanks :)

**Comment by pombredanne** [comment]
anytime :)
